"""create invoice tables

Revision ID: 1e00523cd265
Revises: 3fe23b9c6599
Create Date: 2026-07-29 05:59:18.004405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = '1e00523cd265'
down_revision: Union[str, None] = '3fe23b9c6599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_number_counters',
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('next_seq', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('invoice_date')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('service_period_start', sa.Date(), nullable=True),
    sa.Column('service_period_end', sa.Date(), nullable=True),
    sa.Column('po_number', sa.String(length=100), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_address', sa.String(length=1000), nullable=True),
    sa.Column('customer_contact', sa.String(length=255), nullable=True),
    sa.Column('tax_rate', app.models.base.SQLiteDecimal(), nullable=False),
    sa.Column('deposit_applied', app.models.base.SQLiteDecimal(), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('terms', sa.String(length=2000), nullable=True),
    sa.Column('subtotal_gross', app.models.base.SQLiteDecimal(), nullable=False),
    sa.Column('total_discount', app.models.base.SQLiteDecimal(), nullable=False),
    sa.Column('subtotal_net', app.models.base.SQLiteDecimal(), nullable=False),
    sa.Column('tax_amount', app.models.base.SQLiteDecimal(), nullable=False),
    sa.Column('total', app.models.base.SQLiteDecimal(), nullable=False),
    sa.Column('balance_due', app.models.base.SQLiteDecimal(), nullable=False),
    sa.Column('snapshot_company_name', sa.String(length=255), nullable=True),
    sa.Column('snapshot_company_address', sa.String(length=1000), nullable=True),
    sa.Column('snapshot_tax_reg_number', sa.String(length=100), nullable=True),
    sa.Column('snapshot_payment_instructions', sa.String(length=2000), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('posted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('void_reason', sa.String(length=1000), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('voided_by_user_id', sa.Integer(), nullable=True),
    sa.Column('journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('void_journal_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'posted', 'void')", name='ck_invoices_status'),
    sa.CheckConstraint('CAST(deposit_applied AS NUMERIC) <= CAST(total AS NUMERIC)', name='ck_invoices_deposit_not_over_total'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['posted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['void_journal_entry_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['voided_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number', name='uq_invoices_invoice_number')
    )
    op.create_index(op.f('ix_invoices_invoice_date'), 'invoices', ['invoice_date'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', app.models.base.SQLiteDecimal(), nullable=False),
    sa.Column('rate', app.models.base.SQLiteDecimal(), nullable=False),
    sa.Column('discount_mode', sa.String(length=10), nullable=False),
    sa.Column('discount_amount', app.models.base.SQLiteDecimal(), nullable=False),
    sa.Column('discount_percentage', app.models.base.SQLiteDecimal(), nullable=False),
    sa.Column('line_gross', app.models.base.SQLiteDecimal(), nullable=False),
    sa.Column('line_amount', app.models.base.SQLiteDecimal(), nullable=False),
    sa.Column('hide_qty_rate', sa.Boolean(), nullable=False),
    sa.CheckConstraint("discount_mode IN ('amount', 'percent')", name='ck_invoice_lines_discount_mode'),
    sa.CheckConstraint('CAST(discount_amount AS NUMERIC) <= CAST(line_gross AS NUMERIC)', name='ck_invoice_lines_discount_not_over_gross'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_id', 'line_number', name='uq_invoice_lines_invoice_line_number')
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_table('invoice_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_address', sa.String(length=1000), nullable=True),
    sa.Column('company_tax_reg_number', sa.String(length=100), nullable=True),
    sa.Column('company_logo_path', sa.String(length=500), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('bank_account_name', sa.String(length=255), nullable=True),
    sa.Column('bank_account_number', sa.String(length=100), nullable=True),
    sa.Column('accepted_payment_methods', sa.String(length=500), nullable=True),
    sa.Column('payment_reference_instruction', sa.String(length=500), nullable=True),
    sa.Column('invoice_prefix', sa.String(length=20), nullable=False),
    sa.Column('default_payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('default_tax_rate', app.models.base.SQLiteDecimal(), nullable=False),
    sa.Column('default_notes', sa.String(length=2000), nullable=True),
    sa.Column('default_terms', sa.String(length=2000), nullable=True),
    sa.Column('ar_account_id', sa.Integer(), nullable=True),
    sa.Column('service_revenue_account_id', sa.Integer(), nullable=True),
    sa.Column('tax_payable_account_id', sa.Integer(), nullable=True),
    sa.Column('unearned_revenue_account_id', sa.Integer(), nullable=True),
    sa.Column('sales_discounts_account_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_invoice_settings_singleton'),
    sa.ForeignKeyConstraint(['ar_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['sales_discounts_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['service_revenue_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tax_payable_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['unearned_revenue_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_settings')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_invoices_invoice_date'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('invoice_number_counters')
    # ### end Alembic commands ###
