"""initial schema

Revision ID: 7b7992974c12
Revises: 
Create Date: 2026-07-25 05:43:13.944893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.base


# revision identifiers, used by Alembic.
revision: str = '7b7992974c12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('normal_balance', sa.String(length=10), nullable=False),
    sa.Column('is_cash_account', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("account_type IN ('asset', 'liability', 'equity', 'revenue', 'expense')", name='ck_accounts_account_type'),
    sa.CheckConstraint("normal_balance IN ('debit', 'credit')", name='ck_accounts_normal_balance'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_code'), 'accounts', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('generated_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('generated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("period_type IN ('monthly', 'quarterly', 'annual')", name='ck_generated_reports_period_type'),
    sa.CheckConstraint("report_type IN ('profit_loss', 'balance_sheet', 'cash_flow')", name='ck_generated_reports_report_type'),
    sa.ForeignKeyConstraint(['generated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_type', 'period_type', 'period_start', 'period_end', name='uq_generated_reports_period')
    )
    op.create_index(op.f('ix_generated_reports_period_start'), 'generated_reports', ['period_start'], unique=False)
    op.create_table('reconciliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('statement_balance', app.models.base.SQLiteDecimal(), nullable=False),
    sa.Column('book_balance', app.models.base.SQLiteDecimal(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('reconciled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("period_type IN ('monthly', 'quarterly', 'annual')", name='ck_reconciliations_period_type'),
    sa.CheckConstraint("status IN ('open', 'completed')", name='ck_reconciliations_status'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['reconciled_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_type', 'period_start', 'period_end', 'account_id', name='uq_reconciliations_period_account')
    )
    op.create_index(op.f('ix_reconciliations_period_start'), 'reconciliations', ['period_start'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('memo', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_api_key_id', sa.Integer(), nullable=True),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source IN ('manual', 'webhook')", name='ck_journal_entries_source'),
    sa.ForeignKeyConstraint(['created_by_api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_reference', name='uq_journal_entries_external_reference')
    )
    op.create_index(op.f('ix_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=False)
    op.create_table('journal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit_amount', app.models.base.SQLiteDecimal(), nullable=False),
    sa.Column('credit_amount', app.models.base.SQLiteDecimal(), nullable=False),
    sa.Column('memo', sa.String(length=500), nullable=True),
    sa.CheckConstraint('CAST(debit_amount AS NUMERIC) = 0 OR CAST(credit_amount AS NUMERIC) = 0', name='ck_journal_lines_one_sided'),
    sa.CheckConstraint('CAST(debit_amount AS NUMERIC) > 0 OR CAST(credit_amount AS NUMERIC) > 0', name='ck_journal_lines_nonzero'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_lines_account_id'), 'journal_lines', ['account_id'], unique=False)
    op.create_index(op.f('ix_journal_lines_journal_entry_id'), 'journal_lines', ['journal_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_lines_journal_entry_id'), table_name='journal_lines')
    op.drop_index(op.f('ix_journal_lines_account_id'), table_name='journal_lines')
    op.drop_table('journal_lines')
    op.drop_index(op.f('ix_journal_entries_entry_date'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_reconciliations_period_start'), table_name='reconciliations')
    op.drop_table('reconciliations')
    op.drop_index(op.f('ix_generated_reports_period_start'), table_name='generated_reports')
    op.drop_table('generated_reports')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_accounts_code'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
