"""add is_admin to users

Revision ID: cc370c74bf83
Revises: 7b7992974c12
Create Date: 2026-07-25 07:02:07.234542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc370c74bf83'
down_revision: Union[str, None] = '7b7992974c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'users',
        sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    )
    # Promote the earliest-created user (the original bootstrap admin, on any DB seeded
    # before this migration existed) so upgrading never leaves a deployment with zero admins.
    op.execute(
        "UPDATE users SET is_admin = 1 WHERE id = (SELECT MIN(id) FROM users)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
